### ISSUE TITLE
Plugin not working with 4.7

### ISSUE THREAD

**Issue by jitdev87** [CodeAndWeb/texturepacker-godot-plugin#28]
<img width="1136" height="136" alt="Image" src="https://github.com/user-attachments/assets/51ad1c23-e820-4701-9108-5baae2ee1ddb" />

`Godot Engine v4.7.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started on port 6006 ---
  ERROR: res://addons/codeandweb.texturepacker/texturepacker_import_spritesheet.gd:54 - Parse Error: Not all code paths return a value.
  ERROR: res://addons/codeandweb.texturepacker/codeandweb.texturepacker_importer.gd:0 - Compile Error: Failed to compile depended scripts.
  ERROR: modules/gdscript/gdscript_resource_format.cpp:46 - Failed to load script "res://addons/codeandweb.texturepacker/codeandweb.texturepacker_importer.gd" with error "Compilation failed".
  ERROR: res://addons/codeandweb.texturepacker/codeandweb.texturepacker_importer.gd:33 - Invalid call. Nonexistent function 'new' in base 'GDScript'.
`

**Comment by mxHanks** [comment]
I met the same problem

**Comment by endaye** [comment]
This PR #27  has fixed the issue. Please update to [the latest version](https://store.godotengine.org/asset/codeandweb/texturepacker-importer/).

**Comment by jitdev87** [comment]
Thanks!
